import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages, setRequestLocale } from "next-intl/server";
import { Roboto } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/app/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { type ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import { routing } from "@/i18n/routing";
import { TooltipProvider } from "@/components/ui/tooltip";

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700"], style: ["italic", "normal"] });

export const metadata: Metadata = {
  title: "Starter Kit by @leho-dev",
  description: "Generated by create next app"
};

export default async function LocaleLayout({ children }: { children: ReactNode }) {
  const locale = await getLocale();
  setRequestLocale(locale);

  const messages = await getMessages();

  return (
    <html lang={locale || routing.defaultLocale} suppressHydrationWarning>
      <body className={cn(roboto.className, "w-screen h-screen flex flex-col")}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          <TooltipProvider>
            <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
          </TooltipProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
